import { Zone } from '@/models/Card'
import type { Language } from '@/models/Language'

export type { Language, LanguageOption } from '@/models/Language'
export { LANGUAGES, DEFAULT_LANGUAGE, isLanguage, getLanguageName } from '@/models/Language'

/**
 * Localization configuration for card rendering.
 *
 * A single language picker (default English) drives the whole UI, the text
 * rendered on cards (title, subtitle, action, zone and stat labels) and the
 * language used when exporting PDFs.
 */

/** Localized labels used inside a rendered card. */
export interface CardTextLabels {
  attack: string
  defense: string
  action: string
  noArtwork: string
  untitled: string
}

export const CARD_TEXT_LABELS: Record<Language, CardTextLabels> = {
  EN: {
    attack: 'Attack',
    defense: 'Defense',
    action: 'Action',
    noArtwork: 'No artwork',
    untitled: 'Untitled Card',
  },
  PT: {
    attack: 'Ataque',
    defense: 'Defesa',
    action: 'Ação',
    noArtwork: 'Sem arte',
    untitled: 'Carta sem título',
  },
  FR: {
    attack: 'Attaque',
    defense: 'Défense',
    action: 'Action',
    noArtwork: 'Sans illustration',
    untitled: 'Carte sans titre',
  },
  ES: {
    attack: 'Ataque',
    defense: 'Defensa',
    action: 'Acción',
    noArtwork: 'Sin ilustración',
    untitled: 'Carta sin título',
  },
  DE: {
    attack: 'Angriff',
    defense: 'Verteidigung',
    action: 'Aktion',
    noArtwork: 'Kein Artwork',
    untitled: 'Unbenannte Karte',
  },
  NL: {
    attack: 'Aanval',
    defense: 'Verdediging',
    action: 'Actie',
    noArtwork: 'Geen afbeelding',
    untitled: 'Naamloze kaart',
  },
  IT: {
    attack: 'Attacco',
    defense: 'Difesa',
    action: 'Azione',
    noArtwork: 'Nessuna illustrazione',
    untitled: 'Carta senza titolo',
  },
}

export function getCardTextLabels(language: Language): CardTextLabels {
  return CARD_TEXT_LABELS[language] ?? CARD_TEXT_LABELS.EN
}

/** Localized zone labels shown on cards, badges and the PDF. */
export const ZONE_LABELS: Record<Zone, Record<Language, string>> = {
  [Zone.ATTACK]: {
    EN: 'Attack',
    PT: 'Ataque',
    FR: 'Attaque',
    ES: 'Ataque',
    DE: 'Angriff',
    NL: 'Aanval',
    IT: 'Attacco',
  },
  [Zone.MIDFIELD]: {
    EN: 'Midfield',
    PT: 'Meio-campo',
    FR: 'Milieu de terrain',
    ES: 'Mediocampo',
    DE: 'Mittelfeld',
    NL: 'Middenveld',
    IT: 'Centrocampo',
  },
  [Zone.DEFENSE]: {
    EN: 'Defense',
    PT: 'Defesa',
    FR: 'Défense',
    ES: 'Defensa',
    DE: 'Verteidigung',
    NL: 'Verdediging',
    IT: 'Difesa',
  },
}

export function getZoneLabel(zone: Zone, language: Language): string {
  return ZONE_LABELS[zone]?.[language] ?? ZONE_LABELS[zone]?.EN ?? ''
}

type Messages = Record<Language, string>

/**
 * Every localized UI string. Placeholders use `{name}` and are replaced by
 * `translate(key, language, params)`.
 */
export const MESSAGES = {
  'app.tagline': {
    EN: 'Design printable game cards',
    PT: 'Crie cartas de jogo para impressão',
    FR: 'Créez des cartes de jeu imprimables',
    ES: 'Diseña cartas de juego imprimibles',
    DE: 'Druckbare Spielkarten gestalten',
    NL: 'Ontwerp printbare speelkaarten',
    IT: 'Crea carte da gioco stampabili',
  },
  'app.skipToContent': {
    EN: 'Skip to main content',
    PT: 'Saltar para o conteúdo principal',
    FR: 'Aller au contenu principal',
    ES: 'Saltar al contenido principal',
    DE: 'Zum Hauptinhalt springen',
    NL: 'Naar de hoofdinhoud',
    IT: 'Vai al contenuto principale',
  },
  'language.label': {
    EN: 'Language',
    PT: 'Idioma',
    FR: 'Langue',
    ES: 'Idioma',
    DE: 'Sprache',
    NL: 'Taal',
    IT: 'Lingua',
  },
  'nav.mainLabel': {
    EN: 'Main navigation',
    PT: 'Navegação principal',
    FR: 'Navigation principale',
    ES: 'Navegación principal',
    DE: 'Hauptnavigation',
    NL: 'Hoofdnavigatie',
    IT: 'Navigazione principale',
  },
  'nav.workspace': {
    EN: 'Workspace',
    PT: 'Área de trabalho',
    FR: 'Espace de travail',
    ES: 'Espacio de trabajo',
    DE: 'Arbeitsbereich',
    NL: 'Werkruimte',
    IT: 'Area di lavoro',
  },
  'nav.cards': {
    EN: 'Cards',
    PT: 'Cartas',
    FR: 'Cartes',
    ES: 'Cartas',
    DE: 'Karten',
    NL: 'Kaarten',
    IT: 'Carte',
  },
  'nav.newCard': {
    EN: 'New Card',
    PT: 'Nova Carta',
    FR: 'Nouvelle carte',
    ES: 'Nueva carta',
    DE: 'Neue Karte',
    NL: 'Nieuwe kaart',
    IT: 'Nuova carta',
  },
  'nav.settings': {
    EN: 'Settings',
    PT: 'Configurações',
    FR: 'Paramètres',
    ES: 'Ajustes',
    DE: 'Einstellungen',
    NL: 'Instellingen',
    IT: 'Impostazioni',
  },
  'nav.images': {
    EN: 'Images',
    PT: 'Imagens',
    FR: 'Images',
    ES: 'Imágenes',
    DE: 'Bilder',
    NL: 'Afbeeldingen',
    IT: 'Immagini',
  },

  'common.cancel': {
    EN: 'Cancel',
    PT: 'Cancelar',
    FR: 'Annuler',
    ES: 'Cancelar',
    DE: 'Abbrechen',
    NL: 'Annuleren',
    IT: 'Annulla',
  },
  'common.save': {
    EN: 'Save Card',
    PT: 'Salvar carta',
    FR: 'Enregistrer la carte',
    ES: 'Guardar carta',
    DE: 'Karte speichern',
    NL: 'Kaart opslaan',
    IT: 'Salva carta',
  },
  'common.saving': {
    EN: 'Saving...',
    PT: 'Salvando...',
    FR: 'Enregistrement...',
    ES: 'Guardando...',
    DE: 'Speichern...',
    NL: 'Opslaan...',
    IT: 'Salvataggio...',
  },
  'common.working': {
    EN: 'Working...',
    PT: 'Processando...',
    FR: 'Traitement...',
    ES: 'Procesando...',
    DE: 'Wird ausgeführt...',
    NL: 'Bezig...',
    IT: 'Elaborazione...',
  },
  'common.preview': {
    EN: 'Preview',
    PT: 'Visualizar',
    FR: 'Aperçu',
    ES: 'Vista previa',
    DE: 'Vorschau',
    NL: 'Voorbeeld',
    IT: 'Anteprima',
  },
  'common.generatePdf': {
    EN: 'Generate PDF',
    PT: 'Gerar PDF',
    FR: 'Générer le PDF',
    ES: 'Generar PDF',
    DE: 'PDF erstellen',
    NL: 'PDF genereren',
    IT: 'Genera PDF',
  },
  'common.edit': {
    EN: 'Edit',
    PT: 'Editar',
    FR: 'Modifier',
    ES: 'Editar',
    DE: 'Bearbeiten',
    NL: 'Bewerken',
    IT: 'Modifica',
  },
  'common.delete': {
    EN: 'Delete',
    PT: 'Excluir',
    FR: 'Supprimer',
    ES: 'Eliminar',
    DE: 'Löschen',
    NL: 'Verwijderen',
    IT: 'Elimina',
  },
  'common.export': {
    EN: 'Export',
    PT: 'Exportar',
    FR: 'Exporter',
    ES: 'Exportar',
    DE: 'Exportieren',
    NL: 'Exporteren',
    IT: 'Esporta',
  },
  'common.reset': {
    EN: 'Reset to defaults',
    PT: 'Restaurar padrões',
    FR: 'Réinitialiser',
    ES: 'Restablecer valores',
    DE: 'Zurücksetzen',
    NL: 'Standaardwaarden',
    IT: 'Ripristina predefiniti',
  },
  'common.dismiss': {
    EN: 'Dismiss message',
    PT: 'Fechar mensagem',
    FR: 'Fermer le message',
    ES: 'Cerrar mensaje',
    DE: 'Nachricht schließen',
    NL: 'Bericht sluiten',
    IT: 'Chiudi messaggio',
  },
  'common.selectAll': {
    EN: 'Select all',
    PT: 'Selecionar todas',
    FR: 'Tout sélectionner',
    ES: 'Seleccionar todo',
    DE: 'Alle auswählen',
    NL: 'Alles selecteren',
    IT: 'Seleziona tutto',
  },
  'common.clearSelection': {
    EN: 'Clear selection',
    PT: 'Limpar seleção',
    FR: 'Effacer la sélection',
    ES: 'Borrar selección',
    DE: 'Auswahl aufheben',
    NL: 'Selectie wissen',
    IT: 'Cancella selezione',
  },
  'common.loading': {
    EN: 'Loading...',
    PT: 'Carregando...',
    FR: 'Chargement...',
    ES: 'Cargando...',
    DE: 'Wird geladen...',
    NL: 'Laden...',
    IT: 'Caricamento...',
  },
  'common.backToCards': {
    EN: 'Back to Cards',
    PT: 'Voltar às cartas',
    FR: 'Retour aux cartes',
    ES: 'Volver a las cartas',
    DE: 'Zurück zu den Karten',
    NL: 'Terug naar kaarten',
    IT: 'Torna alle carte',
  },
  'common.optional': {
    EN: 'Optional',
    PT: 'Opcional',
    FR: 'Facultatif',
    ES: 'Opcional',
    DE: 'Optional',
    NL: 'Optioneel',
    IT: 'Opzionale',
  },

  'cards.title': {
    EN: 'Cards',
    PT: 'Cartas',
    FR: 'Cartes',
    ES: 'Cartas',
    DE: 'Karten',
    NL: 'Kaarten',
    IT: 'Carte',
  },
  'cards.subtitleOne': {
    EN: '{count} card in your local collection',
    PT: '{count} carta na sua coleção local',
    FR: '{count} carte dans votre collection locale',
    ES: '{count} carta en tu colección local',
    DE: '{count} Karte in deiner lokalen Sammlung',
    NL: '{count} kaart in je lokale verzameling',
    IT: '{count} carta nella tua collezione locale',
  },
  'cards.subtitleMany': {
    EN: '{count} cards in your local collection',
    PT: '{count} cartas na sua coleção local',
    FR: '{count} cartes dans votre collection locale',
    ES: '{count} cartas en tu colección local',
    DE: '{count} Karten in deiner lokalen Sammlung',
    NL: '{count} kaarten in je lokale verzameling',
    IT: '{count} carte nella tua collezione locale',
  },
  'cards.createNew': {
    EN: 'Create New Card',
    PT: 'Criar nova carta',
    FR: 'Créer une carte',
    ES: 'Crear nueva carta',
    DE: 'Neue Karte erstellen',
    NL: 'Nieuwe kaart maken',
    IT: 'Crea nuova carta',
  },
  'cards.importCsv': {
    EN: 'Import CSV',
    PT: 'Importar CSV',
    FR: 'Importer un CSV',
    ES: 'Importar CSV',
    DE: 'CSV importieren',
    NL: 'CSV importeren',
    IT: 'Importa CSV',
  },
  'cards.importingCsv': {
    EN: 'Importing CSV...',
    PT: 'Importando CSV...',
    FR: 'Importation du CSV...',
    ES: 'Importando CSV...',
    DE: 'CSV wird importiert...',
    NL: 'CSV importeren...',
    IT: 'Importazione CSV...',
  },
  'cards.exportAll': {
    EN: 'Export All as PDF',
    PT: 'Exportar todas em PDF',
    FR: 'Exporter tout en PDF',
    ES: 'Exportar todas a PDF',
    DE: 'Alle als PDF exportieren',
    NL: 'Alles als PDF exporteren',
    IT: 'Esporta tutte in PDF',
  },
  'cards.exportCsv': {
    EN: 'Download CSV',
    PT: 'Descarregar CSV',
    FR: 'Télécharger le CSV',
    ES: 'Descargar CSV',
    DE: 'CSV herunterladen',
    NL: 'CSV downloaden',
    IT: 'Scarica CSV',
  },
  'cards.backupImport': {
    EN: 'Backup & Import',
    PT: 'Backup e importação',
    FR: 'Sauvegarde et import',
    ES: 'Copia e importación',
    DE: 'Backup & Import',
    NL: 'Back-up en import',
    IT: 'Backup e importazione',
  },
  'cards.deleteAll': {
    EN: 'Delete All Cards',
    PT: 'Excluir todas as cartas',
    FR: 'Supprimer toutes les cartes',
    ES: 'Eliminar todas las cartas',
    DE: 'Alle Karten löschen',
    NL: 'Alle kaarten verwijderen',
    IT: 'Elimina tutte le carte',
  },
  'cards.loading': {
    EN: 'Loading cards...',
    PT: 'Carregando cartas...',
    FR: 'Chargement des cartes...',
    ES: 'Cargando cartas...',
    DE: 'Karten werden geladen...',
    NL: 'Kaarten laden...',
    IT: 'Caricamento carte...',
  },
  'cards.emptyTitle': {
    EN: 'No cards created yet.',
    PT: 'Nenhuma carta criada ainda.',
    FR: 'Aucune carte créée pour le moment.',
    ES: 'Todavía no hay cartas creadas.',
    DE: 'Noch keine Karten erstellt.',
    NL: 'Nog geen kaarten gemaakt.',
    IT: 'Nessuna carta creata finora.',
  },
  'cards.emptyMessage': {
    EN: 'Create your first card to see it here. Cards are stored locally in your browser.',
    PT: 'Crie a sua primeira carta para vê-la aqui. As cartas são guardadas localmente no navegador.',
    FR: 'Créez votre première carte pour la voir ici. Les cartes sont stockées localement dans votre navigateur.',
    ES: 'Crea tu primera carta para verla aquí. Las cartas se guardan localmente en tu navegador.',
    DE: 'Erstelle deine erste Karte, um sie hier zu sehen. Karten werden lokal im Browser gespeichert.',
    NL: 'Maak je eerste kaart om die hier te zien. Kaarten worden lokaal in je browser opgeslagen.',
    IT: 'Crea la tua prima carta per vederla qui. Le carte sono salvate localmente nel browser.',
  },
  'cards.emptyAction': {
    EN: 'Create your first card',
    PT: 'Criar a primeira carta',
    FR: 'Créer votre première carte',
    ES: 'Crear tu primera carta',
    DE: 'Erste Karte erstellen',
    NL: 'Eerste kaart maken',
    IT: 'Crea la tua prima carta',
  },
  'cards.chooseCsv': {
    EN: 'Choose a CSV file to import',
    PT: 'Escolha um ficheiro CSV para importar',
    FR: 'Choisir un fichier CSV à importer',
    ES: 'Elige un archivo CSV para importar',
    DE: 'CSV-Datei zum Importieren wählen',
    NL: 'Kies een CSV-bestand om te importeren',
    IT: 'Scegli un file CSV da importare',
  },
  'cards.fallbackBadge': {
    EN: 'No {language} translation — showing English',
    PT: 'Sem tradução em {language} — a mostrar inglês',
    FR: 'Pas de traduction en {language} — affichage en anglais',
    ES: 'Sin traducción al {language} — se muestra en inglés',
    DE: 'Keine {language}-Übersetzung — Englisch wird angezeigt',
    NL: 'Geen {language}-vertaling — Engels wordt getoond',
    IT: 'Nessuna traduzione in {language} — viene mostrato l’inglese',
  },
  'cards.deleteOneTitle': {
    EN: 'Delete this card?',
    PT: 'Excluir esta carta?',
    FR: 'Supprimer cette carte ?',
    ES: '¿Eliminar esta carta?',
    DE: 'Diese Karte löschen?',
    NL: 'Deze kaart verwijderen?',
    IT: 'Eliminare questa carta?',
  },
  'cards.deleteOneMessage': {
    EN: '"{title}" will be permanently removed from this browser.',
    PT: '"{title}" será removida permanentemente deste navegador.',
    FR: '"{title}" sera définitivement supprimée de ce navigateur.',
    ES: '"{title}" se eliminará permanentemente de este navegador.',
    DE: '"{title}" wird dauerhaft aus diesem Browser entfernt.',
    NL: '"{title}" wordt permanent uit deze browser verwijderd.',
    IT: '"{title}" verrà rimossa definitivamente da questo browser.',
  },
  'cards.deleteAllTitle': {
    EN: 'Delete all cards?',
    PT: 'Excluir todas as cartas?',
    FR: 'Supprimer toutes les cartes ?',
    ES: '¿Eliminar todas las cartas?',
    DE: 'Alle Karten löschen?',
    NL: 'Alle kaarten verwijderen?',
    IT: 'Eliminare tutte le carte?',
  },
  'cards.deleteAllMessage': {
    EN: 'All {count} stored in this browser will be permanently removed. This cannot be undone.',
    PT: 'Todas as {count} guardadas neste navegador serão removidas permanentemente. Isto não pode ser desfeito.',
    FR: 'Les {count} stockées dans ce navigateur seront définitivement supprimées. Action irréversible.',
    ES: 'Las {count} guardadas en este navegador se eliminarán permanentemente. No se puede deshacer.',
    DE: 'Alle {count} in diesem Browser werden dauerhaft entfernt. Dies kann nicht rückgängig gemacht werden.',
    NL: 'Alle {count} in deze browser worden permanent verwijderd. Dit kan niet ongedaan worden gemaakt.',
    IT: 'Tutte le {count} salvate in questo browser verranno rimosse definitivamente. L’operazione è irreversibile.',
  },
  'cards.deleteAllConfirm': {
    EN: 'Delete all',
    PT: 'Excluir todas',
    FR: 'Tout supprimer',
    ES: 'Eliminar todo',
    DE: 'Alle löschen',
    NL: 'Alles verwijderen',
    IT: 'Elimina tutte',
  },
  'cards.statusPdfGenerated': {
    EN: 'PDF for "{title}" was generated.',
    PT: 'O PDF de "{title}" foi gerado.',
    FR: 'Le PDF de "{title}" a été généré.',
    ES: 'Se generó el PDF de "{title}".',
    DE: 'PDF für "{title}" wurde erstellt.',
    NL: 'PDF voor "{title}" is gegenereerd.',
    IT: 'PDF di "{title}" generato.',
  },
  'cards.statusPdfMany': {
    EN: 'PDF with {count} cards was generated.',
    PT: 'Foi gerado um PDF com {count} cartas.',
    FR: 'Un PDF de {count} cartes a été généré.',
    ES: 'Se generó un PDF con {count} cartas.',
    DE: 'PDF mit {count} Karten wurde erstellt.',
    NL: 'PDF met {count} kaarten is gegenereerd.',
    IT: 'Generato un PDF con {count} carte.',
  },
  'cards.statusDeleted': {
    EN: '"{title}" was deleted.',
    PT: '"{title}" foi excluída.',
    FR: '"{title}" a été supprimée.',
    ES: '"{title}" se eliminó.',
    DE: '"{title}" wurde gelöscht.',
    NL: '"{title}" is verwijderd.',
    IT: '"{title}" è stata eliminata.',
  },
  'cards.statusAllDeleted': {
    EN: 'All cards were deleted from this browser.',
    PT: 'Todas as cartas foram excluídas deste navegador.',
    FR: 'Toutes les cartes ont été supprimées de ce navigateur.',
    ES: 'Todas las cartas se eliminaron de este navegador.',
    DE: 'Alle Karten wurden aus diesem Browser gelöscht.',
    NL: 'Alle kaarten zijn uit deze browser verwijderd.',
    IT: 'Tutte le carte sono state eliminate da questo browser.',
  },
  'cards.statusCsvImported': {
    EN: 'Created {count} cards from the CSV.',
    PT: 'Foram criadas {count} cartas a partir do CSV.',
    FR: '{count} cartes créées à partir du CSV.',
    ES: 'Se crearon {count} cartas desde el CSV.',
    DE: '{count} Karten aus der CSV erstellt.',
    NL: '{count} kaarten uit de CSV gemaakt.',
    IT: 'Create {count} carte dal CSV.',
  },
  'cards.statusCsvExported': {
    EN: 'CSV with {count} cards was generated.',
    PT: 'Foi gerado um CSV com {count} cartas.',
    FR: 'Un CSV de {count} cartes a été généré.',
    ES: 'Se generó un CSV con {count} cartas.',
    DE: 'CSV mit {count} Karten wurde erstellt.',
    NL: 'CSV met {count} kaarten is gegenereerd.',
    IT: 'Generato un CSV con {count} carte.',
  },
  'cards.statusCsvExportFailed': {
    EN: 'The CSV could not be generated. Please try again.',
    PT: 'Não foi possível gerar o CSV. Tente novamente.',
    FR: 'Le CSV n’a pas pu être généré. Veuillez réessayer.',
    ES: 'No se pudo generar el CSV. Inténtalo de nuevo.',
    DE: 'Die CSV konnte nicht erstellt werden. Bitte versuche es erneut.',
    NL: 'De CSV kon niet worden gegenereerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile generare il CSV. Riprova.',
  },
  'cards.statusPdfFailed': {
    EN: 'The PDF could not be generated. Please try again.',
    PT: 'Não foi possível gerar o PDF. Tente novamente.',
    FR: 'Le PDF n’a pas pu être généré. Veuillez réessayer.',
    ES: 'No se pudo generar el PDF. Inténtalo de nuevo.',
    DE: 'Das PDF konnte nicht erstellt werden. Bitte versuche es erneut.',
    NL: 'De PDF kon niet worden gegenereerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile generare il PDF. Riprova.',
  },
  'cards.statusDeleteFailed': {
    EN: 'The card could not be deleted. Please try again.',
    PT: 'Não foi possível excluir a carta. Tente novamente.',
    FR: 'La carte n’a pas pu être supprimée. Veuillez réessayer.',
    ES: 'No se pudo eliminar la carta. Inténtalo de nuevo.',
    DE: 'Die Karte konnte nicht gelöscht werden. Bitte versuche es erneut.',
    NL: 'De kaart kon niet worden verwijderd. Probeer het opnieuw.',
    IT: 'Non è stato possibile eliminare la carta. Riprova.',
  },
  'cards.statusDeleteAllFailed': {
    EN: 'The cards could not be deleted. Please try again.',
    PT: 'Não foi possível excluir as cartas. Tente novamente.',
    FR: 'Les cartes n’ont pas pu être supprimées. Veuillez réessayer.',
    ES: 'No se pudieron eliminar las cartas. Inténtalo de nuevo.',
    DE: 'Die Karten konnten nicht gelöscht werden. Bitte versuche es erneut.',
    NL: 'De kaarten konden niet worden verwijderd. Probeer het opnieuw.',
    IT: 'Non è stato possibile eliminare le carte. Riprova.',
  },
  'cards.statusCsvSaveFailed': {
    EN: 'The cards from the CSV could not be saved.',
    PT: 'Não foi possível guardar as cartas do CSV.',
    FR: 'Les cartes du CSV n’ont pas pu être enregistrées.',
    ES: 'No se pudieron guardar las cartas del CSV.',
    DE: 'Die Karten aus der CSV konnten nicht gespeichert werden.',
    NL: 'De kaarten uit de CSV konden niet worden opgeslagen.',
    IT: 'Non è stato possibile salvare le carte del CSV.',
  },
  'cards.statusCsvImportFailed': {
    EN: 'The CSV file could not be imported. Please try again.',
    PT: 'Não foi possível importar o ficheiro CSV. Tente novamente.',
    FR: 'Le fichier CSV n’a pas pu être importé. Veuillez réessayer.',
    ES: 'No se pudo importar el archivo CSV. Inténtalo de nuevo.',
    DE: 'Die CSV-Datei konnte nicht importiert werden. Bitte versuche es erneut.',
    NL: 'Het CSV-bestand kon niet worden geïmporteerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile importare il file CSV. Riprova.',
  },
  'cards.ariaDelete': {
    EN: 'Delete {title}',
    PT: 'Excluir {title}',
    FR: 'Supprimer {title}',
    ES: 'Eliminar {title}',
    DE: '{title} löschen',
    NL: '{title} verwijderen',
    IT: 'Elimina {title}',
  },
  'cards.ariaEdit': {
    EN: 'Edit {title}',
    PT: 'Editar {title}',
    FR: 'Modifier {title}',
    ES: 'Editar {title}',
    DE: '{title} bearbeiten',
    NL: '{title} bewerken',
    IT: 'Modifica {title}',
  },
  'cards.ariaPreview': {
    EN: 'Preview {title}',
    PT: 'Visualizar {title}',
    FR: 'Aperçu de {title}',
    ES: 'Vista previa de {title}',
    DE: 'Vorschau von {title}',
    NL: 'Voorbeeld van {title}',
    IT: 'Anteprima di {title}',
  },
  'cards.ariaPdf': {
    EN: 'Export PDF for {title}',
    PT: 'Exportar PDF de {title}',
    FR: 'Exporter le PDF de {title}',
    ES: 'Exportar PDF de {title}',
    DE: 'PDF für {title} exportieren',
    NL: 'PDF voor {title} exporteren',
    IT: 'Esporta PDF di {title}',
  },

  'images.title': {
    EN: 'Images',
    PT: 'Imagens',
    FR: 'Images',
    ES: 'Imágenes',
    DE: 'Bilder',
    NL: 'Afbeeldingen',
    IT: 'Immagini',
  },
  'images.subtitle': {
    EN: 'Manage the artwork available to your cards and CSV imports.',
    PT: 'Gerir as imagens disponíveis para as cartas e importações CSV.',
    FR: 'Gérez les images disponibles pour vos cartes et vos imports CSV.',
    ES: 'Gestiona las imágenes disponibles para tus cartas e importaciones CSV.',
    DE: 'Verwalte die Bilder für deine Karten und CSV-Importe.',
    NL: 'Beheer de afbeeldingen voor je kaarten en CSV-imports.',
    IT: 'Gestisci le immagini disponibili per le carte e le importazioni CSV.',
  },
  'images.upload': {
    EN: 'Upload images',
    PT: 'Carregar imagens',
    FR: 'Téléverser des images',
    ES: 'Subir imágenes',
    DE: 'Bilder hochladen',
    NL: 'Afbeeldingen uploaden',
    IT: 'Carica immagini',
  },
  'images.uploading': {
    EN: 'Uploading...',
    PT: 'A carregar...',
    FR: 'Téléversement...',
    ES: 'Subiendo...',
    DE: 'Wird hochgeladen...',
    NL: 'Uploaden...',
    IT: 'Caricamento...',
  },
  'images.chooseFiles': {
    EN: 'Choose one or more images',
    PT: 'Escolha uma ou mais imagens',
    FR: 'Choisir une ou plusieurs images',
    ES: 'Elige una o más imágenes',
    DE: 'Ein oder mehrere Bilder wählen',
    NL: 'Kies een of meer afbeeldingen',
    IT: 'Scegli una o più immagini',
  },
  'images.sampleSection': {
    EN: 'Sample images',
    PT: 'Imagens de exemplo',
    FR: 'Images d’exemple',
    ES: 'Imágenes de ejemplo',
    DE: 'Beispielbilder',
    NL: 'Voorbeeldafbeeldingen',
    IT: 'Immagini di esempio',
  },
  'images.localSection': {
    EN: 'My images',
    PT: 'As minhas imagens',
    FR: 'Mes images',
    ES: 'Mis imágenes',
    DE: 'Meine Bilder',
    NL: 'Mijn afbeeldingen',
    IT: 'Le mie immagini',
  },
  'images.empty': {
    EN: 'No images uploaded yet.',
    PT: 'Ainda não há imagens carregadas.',
    FR: 'Aucune image téléversée pour le moment.',
    ES: 'Todavía no has subido imágenes.',
    DE: 'Noch keine Bilder hochgeladen.',
    NL: 'Nog geen afbeeldingen geüpload.',
    IT: 'Nessuna immagine caricata finora.',
  },
  'images.emptyHint': {
    EN: 'Upload PNG, JPEG or WebP files to use them on cards and reference them from CSV imports.',
    PT: 'Carregue ficheiros PNG, JPEG ou WebP para os usar nas cartas e referenciar em importações CSV.',
    FR: 'Téléversez des fichiers PNG, JPEG ou WebP pour les utiliser sur les cartes et les référencer dans les imports CSV.',
    ES: 'Sube archivos PNG, JPEG o WebP para usarlos en las cartas y referenciarlos en importaciones CSV.',
    DE: 'Lade PNG-, JPEG- oder WebP-Dateien hoch, um sie auf Karten zu verwenden und in CSV-Importen zu referenzieren.',
    NL: 'Upload PNG-, JPEG- of WebP-bestanden om ze op kaarten te gebruiken en in CSV-imports te verwijzen.',
    IT: 'Carica file PNG, JPEG o WebP per usarli sulle carte e referenziarli negli import CSV.',
  },
  'images.hint': {
    EN: 'PNG, JPEG or WebP up to 5 MB each. In a CSV, put the file name in the image column (for example img1.jpeg).',
    PT: 'PNG, JPEG ou WebP até 5 MB cada. Num CSV, coloque o nome do ficheiro na coluna image (por exemplo img1.jpeg).',
    FR: 'PNG, JPEG ou WebP jusqu’à 5 Mo chacun. Dans un CSV, indiquez le nom du fichier dans la colonne image (par exemple img1.jpeg).',
    ES: 'PNG, JPEG o WebP de hasta 5 MB cada uno. En un CSV, escribe el nombre del archivo en la columna image (por ejemplo img1.jpeg).',
    DE: 'PNG, JPEG oder WebP bis 5 MB pro Datei. In einer CSV den Dateinamen in die Spalte image schreiben (zum Beispiel img1.jpeg).',
    NL: 'PNG, JPEG of WebP tot 5 MB per stuk. Zet in een CSV de bestandsnaam in de kolom image (bijvoorbeeld img1.jpeg).',
    IT: 'PNG, JPEG o WebP fino a 5 MB ciascuno. In un CSV, inserisci il nome del file nella colonna image (ad esempio img1.jpeg).',
  },
  'images.badgeSample': {
    EN: 'Sample',
    PT: 'Exemplo',
    FR: 'Exemple',
    ES: 'Ejemplo',
    DE: 'Beispiel',
    NL: 'Voorbeeld',
    IT: 'Esempio',
  },
  'images.badgeUploaded': {
    EN: 'Uploaded',
    PT: 'Carregada',
    FR: 'Téléversée',
    ES: 'Subida',
    DE: 'Hochgeladen',
    NL: 'Geüpload',
    IT: 'Caricata',
  },
  'images.copyName': {
    EN: 'Copy file name',
    PT: 'Copiar nome do ficheiro',
    FR: 'Copier le nom du fichier',
    ES: 'Copiar nombre del archivo',
    DE: 'Dateinamen kopieren',
    NL: 'Bestandsnaam kopiëren',
    IT: 'Copia nome file',
  },
  'images.copied': {
    EN: 'File name copied: {name}',
    PT: 'Nome do ficheiro copiado: {name}',
    FR: 'Nom du fichier copié : {name}',
    ES: 'Nombre de archivo copiado: {name}',
    DE: 'Dateiname kopiert: {name}',
    NL: 'Bestandsnaam gekopieerd: {name}',
    IT: 'Nome file copiato: {name}',
  },
  'images.copyFailed': {
    EN: 'The file name could not be copied.',
    PT: 'Não foi possível copiar o nome do ficheiro.',
    FR: 'Le nom du fichier n’a pas pu être copié.',
    ES: 'No se pudo copiar el nombre del archivo.',
    DE: 'Der Dateiname konnte nicht kopiert werden.',
    NL: 'De bestandsnaam kon niet worden gekopieerd.',
    IT: 'Non è stato possibile copiare il nome del file.',
  },
  'images.deleteTitle': {
    EN: 'Delete this image?',
    PT: 'Excluir esta imagem?',
    FR: 'Supprimer cette image ?',
    ES: '¿Eliminar esta imagen?',
    DE: 'Dieses Bild löschen?',
    NL: 'Deze afbeelding verwijderen?',
    IT: 'Eliminare questa immagine?',
  },
  'images.deleteMessage': {
    EN: '"{name}" will be removed from your local image library. Cards already using it keep their own copy.',
    PT: '"{name}" será removida da sua biblioteca local. As cartas que já a usam mantêm a sua cópia.',
    FR: '"{name}" sera supprimée de votre bibliothèque locale. Les cartes qui l’utilisent déjà conservent leur copie.',
    ES: '"{name}" se eliminará de tu biblioteca local. Las cartas que ya la usan conservan su copia.',
    DE: '"{name}" wird aus deiner lokalen Bibliothek entfernt. Karten, die es bereits verwenden, behalten ihre eigene Kopie.',
    NL: '"{name}" wordt uit je lokale bibliotheek verwijderd. Kaarten die het al gebruiken behouden hun eigen kopie.',
    IT: '"{name}" verrà rimossa dalla libreria locale. Le carte che la usano già mantengono la propria copia.',
  },
  'images.statusUploaded': {
    EN: 'Added {count} image(s).',
    PT: 'Adicionada(s) {count} imagem(ns).',
    FR: '{count} image(s) ajoutée(s).',
    ES: 'Se añadieron {count} imagen(es).',
    DE: '{count} Bild(er) hinzugefügt.',
    NL: '{count} afbeelding(en) toegevoegd.',
    IT: 'Aggiunte {count} immagine/i.',
  },
  'images.statusDeleted': {
    EN: '"{name}" was deleted.',
    PT: '"{name}" foi excluída.',
    FR: '"{name}" a été supprimée.',
    ES: '"{name}" se eliminó.',
    DE: '"{name}" wurde gelöscht.',
    NL: '"{name}" is verwijderd.',
    IT: '"{name}" è stata eliminata.',
  },
  'images.uploadFailed': {
    EN: 'Some images could not be uploaded.',
    PT: 'Algumas imagens não puderam ser carregadas.',
    FR: 'Certaines images n’ont pas pu être téléversées.',
    ES: 'Algunas imágenes no se pudieron subir.',
    DE: 'Einige Bilder konnten nicht hochgeladen werden.',
    NL: 'Sommige afbeeldingen konden niet worden geüpload.',
    IT: 'Alcune immagini non sono state caricate.',
  },
  'images.downloadZip': {
    EN: 'Download all images (ZIP)',
    PT: 'Descarregar todas as imagens (ZIP)',
    FR: 'Télécharger toutes les images (ZIP)',
    ES: 'Descargar todas las imágenes (ZIP)',
    DE: 'Alle Bilder herunterladen (ZIP)',
    NL: 'Alle afbeeldingen downloaden (ZIP)',
    IT: 'Scarica tutte le immagini (ZIP)',
  },
  'images.zipping': {
    EN: 'Preparing ZIP...',
    PT: 'A preparar ZIP...',
    FR: 'Préparation du ZIP...',
    ES: 'Preparando ZIP...',
    DE: 'ZIP wird vorbereitet...',
    NL: 'ZIP voorbereiden...',
    IT: 'Preparazione ZIP...',
  },
  'images.statusZip': {
    EN: 'ZIP with {count} image(s) was generated.',
    PT: 'Foi gerado um ZIP com {count} imagem(ns).',
    FR: 'ZIP de {count} image(s) généré.',
    ES: 'Se generó un ZIP con {count} imagen(es).',
    DE: 'ZIP mit {count} Bild(ern) wurde erstellt.',
    NL: 'ZIP met {count} afbeelding(en) is gegenereerd.',
    IT: 'Generato un ZIP con {count} immagine/i.',
  },
  'images.zipFailed': {
    EN: 'The ZIP could not be generated. Please try again.',
    PT: 'Não foi possível gerar o ZIP. Tente novamente.',
    FR: 'Le ZIP n’a pas pu être généré. Veuillez réessayer.',
    ES: 'No se pudo generar el ZIP. Inténtalo de nuevo.',
    DE: 'Die ZIP konnte nicht erstellt werden. Bitte versuche es erneut.',
    NL: 'De ZIP kon niet worden gegenereerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile generare il ZIP. Riprova.',
  },

  'export.title': {
    EN: 'Export Cards as PDF',
    PT: 'Exportar cartas em PDF',
    FR: 'Exporter les cartes en PDF',
    ES: 'Exportar cartas a PDF',
    DE: 'Karten als PDF exportieren',
    NL: 'Kaarten als PDF exporteren',
    IT: 'Esporta carte in PDF',
  },
  'export.description': {
    EN: 'Choose which cards to include. Each card is exported on its own page at the exact card size, with no margins, in the selected language.',
    PT: 'Escolha as cartas a incluir. Cada carta é exportada numa página própria com o tamanho exato da carta, sem margens, no idioma selecionado.',
    FR: 'Choisissez les cartes à inclure. Chaque carte est exportée sur sa propre page à sa taille exacte, sans marges, dans la langue sélectionnée.',
    ES: 'Elige qué cartas incluir. Cada carta se exporta en su propia página con el tamaño exacto, sin márgenes, en el idioma seleccionado.',
    DE: 'Wähle die Karten aus. Jede Karte wird auf einer eigenen Seite in exakter Kartengröße ohne Ränder in der ausgewählten Sprache exportiert.',
    NL: 'Kies welke kaarten je wilt opnemen. Elke kaart wordt op een eigen pagina op exact kaartformaat geëxporteerd, zonder marges, in de geselecteerde taal.',
    IT: 'Scegli quali carte includere. Ogni carta viene esportata su una pagina dedicata alle dimensioni esatte, senza margini, nella lingua selezionata.',
  },
  'export.cardsToExport': {
    EN: 'Cards to export',
    PT: 'Cartas a exportar',
    FR: 'Cartes à exporter',
    ES: 'Cartas a exportar',
    DE: 'Zu exportierende Karten',
    NL: 'Kaarten om te exporteren',
    IT: 'Carte da esportare',
  },
  'export.selectedCount': {
    EN: '{selected} of {total} selected',
    PT: '{selected} de {total} selecionadas',
    FR: '{selected} sur {total} sélectionnées',
    ES: '{selected} de {total} seleccionadas',
    DE: '{selected} von {total} ausgewählt',
    NL: '{selected} van {total} geselecteerd',
    IT: '{selected} di {total} selezionate',
  },
  'dialog.close': {
    EN: 'Close dialog',
    PT: 'Fechar janela',
    FR: 'Fermer la boîte de dialogue',
    ES: 'Cerrar diálogo',
    DE: 'Dialog schließen',
    NL: 'Dialoog sluiten',
    IT: 'Chiudi finestra',
  },

  'editor.newTitle': {
    EN: 'New Card',
    PT: 'Nova carta',
    FR: 'Nouvelle carte',
    ES: 'Nueva carta',
    DE: 'Neue Karte',
    NL: 'Nieuwe kaart',
    IT: 'Nuova carta',
  },
  'editor.editTitle': {
    EN: 'Edit Card',
    PT: 'Editar carta',
    FR: 'Modifier la carte',
    ES: 'Editar carta',
    DE: 'Karte bearbeiten',
    NL: 'Kaart bewerken',
    IT: 'Modifica carta',
  },
  'editor.subtitle': {
    EN: 'Fill in the card details and watch the live preview update as you type.',
    PT: 'Preencha os detalhes da carta e veja a pré-visualização atualizar enquanto escreve.',
    FR: 'Remplissez les détails de la carte et regardez l’aperçu se mettre à jour en direct.',
    ES: 'Completa los detalles de la carta y mira la vista previa actualizarse al escribir.',
    DE: 'Fülle die Kartendetails aus und beobachte die Live-Vorschau beim Tippen.',
    NL: 'Vul de kaartgegevens in en zie het voorbeeld direct bijwerken tijdens het typen.',
    IT: 'Compila i dettagli della carta e guarda l’anteprima aggiornarsi in tempo reale.',
  },
  'editor.loading': {
    EN: 'Loading card...',
    PT: 'Carregando carta...',
    FR: 'Chargement de la carte...',
    ES: 'Cargando carta...',
    DE: 'Karte wird geladen...',
    NL: 'Kaart laden...',
    IT: 'Caricamento carta...',
  },
  'editor.livePreview': {
    EN: 'Live Preview',
    PT: 'Pré-visualização',
    FR: 'Aperçu en direct',
    ES: 'Vista previa en vivo',
    DE: 'Live-Vorschau',
    NL: 'Live voorbeeld',
    IT: 'Anteprima live',
  },
  'editor.notFoundTitle': {
    EN: 'Card not found.',
    PT: 'Carta não encontrada.',
    FR: 'Carte introuvable.',
    ES: 'Carta no encontrada.',
    DE: 'Karte nicht gefunden.',
    NL: 'Kaart niet gevonden.',
    IT: 'Carta non trovata.',
  },
  'editor.notFoundMessage': {
    EN: 'This card may have been deleted from this browser.',
    PT: 'Esta carta pode ter sido excluída deste navegador.',
    FR: 'Cette carte a peut-être été supprimée de ce navigateur.',
    ES: 'Es posible que esta carta se haya eliminado de este navegador.',
    DE: 'Diese Karte wurde möglicherweise aus diesem Browser gelöscht.',
    NL: 'Deze kaart is mogelijk uit deze browser verwijderd.',
    IT: 'Questa carta potrebbe essere stata eliminata da questo browser.',
  },
  'editor.statusFixFields': {
    EN: 'Please fix the highlighted fields.',
    PT: 'Corrija os campos destacados.',
    FR: 'Veuillez corriger les champs en surbrillance.',
    ES: 'Corrige los campos resaltados.',
    DE: 'Bitte korrigiere die markierten Felder.',
    NL: 'Corrigeer de gemarkeerde velden.',
    IT: 'Correggi i campi evidenziati.',
  },
  'editor.statusSaveFailed': {
    EN: 'The card could not be saved. Please try again.',
    PT: 'Não foi possível guardar a carta. Tente novamente.',
    FR: 'La carte n’a pas pu être enregistrée. Veuillez réessayer.',
    ES: 'No se pudo guardar la carta. Inténtalo de nuevo.',
    DE: 'Die Karte konnte nicht gespeichert werden. Bitte versuche es erneut.',
    NL: 'De kaart kon niet worden opgeslagen. Probeer het opnieuw.',
    IT: 'Non è stato possibile salvare la carta. Riprova.',
  },
  'editor.statusPdfSuccess': {
    EN: 'PDF generated successfully.',
    PT: 'PDF gerado com sucesso.',
    FR: 'PDF généré avec succès.',
    ES: 'PDF generado correctamente.',
    DE: 'PDF erfolgreich erstellt.',
    NL: 'PDF succesvol gegenereerd.',
    IT: 'PDF generato correttamente.',
  },
  'editor.translationHint': {
    EN: 'Editing {language}. Leave a field empty to fall back to the English text.',
    PT: 'A editar {language}. Deixe um campo vazio para usar o texto em inglês.',
    FR: 'Édition en {language}. Laissez un champ vide pour utiliser le texte anglais.',
    ES: 'Editando en {language}. Deja un campo vacío para usar el texto en inglés.',
    DE: 'Bearbeitung auf {language}. Lässt du ein Feld leer, wird der englische Text verwendet.',
    NL: 'Bewerken in het {language}. Laat een veld leeg om de Engelse tekst te gebruiken.',
    IT: 'Modifica in {language}. Lascia un campo vuoto per usare il testo inglese.',
  },
  'editor.copyEnglish': {
    EN: 'Copy English text',
    PT: 'Copiar texto em inglês',
    FR: 'Copier le texte anglais',
    ES: 'Copiar texto en inglés',
    DE: 'Englischen Text übernehmen',
    NL: 'Engelse tekst kopiëren',
    IT: 'Copia il testo inglese',
  },
  'editor.statusCopied': {
    EN: 'English text copied to {language}.',
    PT: 'Texto em inglês copiado para {language}.',
    FR: 'Texte anglais copié vers {language}.',
    ES: 'Texto en inglés copiado a {language}.',
    DE: 'Englischer Text nach {language} kopiert.',
    NL: 'Engelse tekst gekopieerd naar {language}.',
    IT: 'Testo inglese copiato in {language}.',
  },

  'field.title': {
    EN: 'Title',
    PT: 'Título',
    FR: 'Titre',
    ES: 'Título',
    DE: 'Titel',
    NL: 'Titel',
    IT: 'Titolo',
  },
  'field.subtitle': {
    EN: 'Subtitle',
    PT: 'Subtítulo',
    FR: 'Sous-titre',
    ES: 'Subtítulo',
    DE: 'Untertitel',
    NL: 'Ondertitel',
    IT: 'Sottotitolo',
  },
  'field.attack': {
    EN: 'Attack',
    PT: 'Ataque',
    FR: 'Attaque',
    ES: 'Ataque',
    DE: 'Angriff',
    NL: 'Aanval',
    IT: 'Attacco',
  },
  'field.defense': {
    EN: 'Defense',
    PT: 'Defesa',
    FR: 'Défense',
    ES: 'Defensa',
    DE: 'Verteidigung',
    NL: 'Verdediging',
    IT: 'Difesa',
  },
  'field.action': {
    EN: 'Action',
    PT: 'Ação',
    FR: 'Action',
    ES: 'Acción',
    DE: 'Aktion',
    NL: 'Actie',
    IT: 'Azione',
  },
  'field.image': {
    EN: 'Image',
    PT: 'Imagem',
    FR: 'Image',
    ES: 'Imagen',
    DE: 'Bild',
    NL: 'Afbeelding',
    IT: 'Immagine',
  },
  'field.zone': {
    EN: 'Zone',
    PT: 'Zona',
    FR: 'Zone',
    ES: 'Zona',
    DE: 'Zone',
    NL: 'Zone',
    IT: 'Zona',
  },
  'field.stars': {
    EN: 'Stars',
    PT: 'Estrelas',
    FR: 'Étoiles',
    ES: 'Estrellas',
    DE: 'Sterne',
    NL: 'Sterren',
    IT: 'Stelle',
  },
  'field.starOne': {
    EN: '{count} star',
    PT: '{count} estrela',
    FR: '{count} étoile',
    ES: '{count} estrella',
    DE: '{count} Stern',
    NL: '{count} ster',
    IT: '{count} stella',
  },
  'field.starMany': {
    EN: '{count} stars',
    PT: '{count} estrelas',
    FR: '{count} étoiles',
    ES: '{count} estrellas',
    DE: '{count} Sterne',
    NL: '{count} sterren',
    IT: '{count} stelle',
  },
  'zone.attackDescription': {
    EN: 'Aggressive red theme for frontline fighters.',
    PT: 'Tema vermelho agressivo para combatentes de linha de frente.',
    FR: 'Thème rouge agressif pour les combattants de première ligne.',
    ES: 'Tema rojo agresivo para combatientes de primera línea.',
    DE: 'Aggressives rotes Thema für Kämpfer an der Front.',
    NL: 'Agressief rood thema voor frontlijnvechters.',
    IT: 'Tema rosso aggressivo per i combattenti in prima linea.',
  },
  'zone.midfieldDescription': {
    EN: 'Balanced green theme for strategists and supports.',
    PT: 'Tema verde equilibrado para estrategas e suportes.',
    FR: 'Thème vert équilibré pour stratèges et soutiens.',
    ES: 'Tema verde equilibrado para estrategas y apoyos.',
    DE: 'Ausgewogenes grünes Thema für Strategen und Unterstützer.',
    NL: 'Gebalanceerd groen thema voor strategen en supporters.',
    IT: 'Tema verde equilibrato per strateghi e supporti.',
  },
  'zone.defenseDescription': {
    EN: 'Sturdy blue theme for guardians and sentinels.',
    PT: 'Tema azul robusto para guardiões e sentinelas.',
    FR: 'Thème bleu robuste pour gardiens et sentinelles.',
    ES: 'Tema azul resistente para guardianes y centinelas.',
    DE: 'Robustes blaues Thema für Wächter und Wachposten.',
    NL: 'Stevig blauw thema voor beschermers en schildwachten.',
    IT: 'Tema blu solido per guardiani e sentinelle.',
  },

  'image.upload': {
    EN: 'Upload image',
    PT: 'Carregar imagem',
    FR: 'Téléverser une image',
    ES: 'Subir imagen',
    DE: 'Bild hochladen',
    NL: 'Afbeelding uploaden',
    IT: 'Carica immagine',
  },
  'image.change': {
    EN: 'Change image',
    PT: 'Alterar imagem',
    FR: 'Changer l’image',
    ES: 'Cambiar imagen',
    DE: 'Bild ändern',
    NL: 'Afbeelding wijzigen',
    IT: 'Cambia immagine',
  },
  'image.remove': {
    EN: 'Remove image',
    PT: 'Remover imagem',
    FR: 'Supprimer l’image',
    ES: 'Quitar imagen',
    DE: 'Bild entfernen',
    NL: 'Afbeelding verwijderen',
    IT: 'Rimuovi immagine',
  },
  'image.processing': {
    EN: 'Processing image...',
    PT: 'A processar imagem...',
    FR: 'Traitement de l’image...',
    ES: 'Procesando imagen...',
    DE: 'Bild wird verarbeitet...',
    NL: 'Afbeelding verwerken...',
    IT: 'Elaborazione immagine...',
  },
  'image.hint': {
    EN: 'PNG, JPEG or WebP up to 5 MB. Images are stored locally in your browser.',
    PT: 'PNG, JPEG ou WebP até 5 MB. As imagens são guardadas localmente no navegador.',
    FR: 'PNG, JPEG ou WebP jusqu’à 5 Mo. Les images sont stockées localement dans votre navigateur.',
    ES: 'PNG, JPEG o WebP de hasta 5 MB. Las imágenes se guardan localmente en tu navegador.',
    DE: 'PNG, JPEG oder WebP bis 5 MB. Bilder werden lokal im Browser gespeichert.',
    NL: 'PNG, JPEG of WebP tot 5 MB. Afbeeldingen worden lokaal in je browser opgeslagen.',
    IT: 'PNG, JPEG o WebP fino a 5 MB. Le immagini sono salvate localmente nel browser.',
  },
  'image.selectedAlt': {
    EN: 'Selected card artwork',
    PT: 'Arte selecionada da carta',
    FR: 'Illustration sélectionnée de la carte',
    ES: 'Ilustración seleccionada de la carta',
    DE: 'Ausgewähltes Kartenbild',
    NL: 'Geselecteerde kaartafbeelding',
    IT: 'Illustrazione selezionata della carta',
  },
  'image.artworkAlt': {
    EN: 'Artwork for {title}',
    PT: 'Arte de {title}',
    FR: 'Illustration de {title}',
    ES: 'Ilustración de {title}',
    DE: 'Artwork für {title}',
    NL: 'Afbeelding voor {title}',
    IT: 'Illustrazione di {title}',
  },

  'preview.ariaCard': {
    EN: 'Card: {title}, {zone} zone, {stars} of 3 stars',
    PT: 'Carta: {title}, zona {zone}, {stars} de 3 estrelas',
    FR: 'Carte : {title}, zone {zone}, {stars} sur 3 étoiles',
    ES: 'Carta: {title}, zona {zone}, {stars} de 3 estrellas',
    DE: 'Karte: {title}, Zone {zone}, {stars} von 3 Sternen',
    NL: 'Kaart: {title}, zone {zone}, {stars} van 3 sterren',
    IT: 'Carta: {title}, zona {zone}, {stars} di 3 stelle',
  },

  'settings.title': {
    EN: 'Settings',
    PT: 'Configurações',
    FR: 'Paramètres',
    ES: 'Ajustes',
    DE: 'Einstellungen',
    NL: 'Instellingen',
    IT: 'Impostazioni',
  },
  'settings.subtitle': {
    EN: 'Configure PDF output, back up your cards and manage local data.',
    PT: 'Configure a exportação em PDF, faça cópias de segurança e gerencie os dados locais.',
    FR: 'Configurez l’export PDF, sauvegardez vos cartes et gérez les données locales.',
    ES: 'Configura la exportación a PDF, haz copias de seguridad y gestiona los datos locales.',
    DE: 'Konfiguriere die PDF-Ausgabe, sichere deine Karten und verwalte lokale Daten.',
    NL: 'Configureer PDF-uitvoer, maak back-ups en beheer lokale gegevens.',
    IT: 'Configura l’esportazione PDF, esegui backup e gestisci i dati locali.',
  },
  'settings.pdfPanel': {
    EN: 'PDF & Print',
    PT: 'PDF e impressão',
    FR: 'PDF et impression',
    ES: 'PDF e impresión',
    DE: 'PDF & Druck',
    NL: 'PDF en afdrukken',
    IT: 'PDF e stampa',
  },
  'settings.cardWidth': {
    EN: 'Card width (mm)',
    PT: 'Largura da carta (mm)',
    FR: 'Largeur de la carte (mm)',
    ES: 'Ancho de la carta (mm)',
    DE: 'Kartenbreite (mm)',
    NL: 'Kaartbreedte (mm)',
    IT: 'Larghezza carta (mm)',
  },
  'settings.cardHeight': {
    EN: 'Card height (mm)',
    PT: 'Altura da carta (mm)',
    FR: 'Hauteur de la carte (mm)',
    ES: 'Alto de la carta (mm)',
    DE: 'Kartenhöhe (mm)',
    NL: 'Kaarthoogte (mm)',
    IT: 'Altezza carta (mm)',
  },
  'settings.imageQuality': {
    EN: 'Image quality',
    PT: 'Qualidade da imagem',
    FR: 'Qualité de l’image',
    ES: 'Calidad de imagen',
    DE: 'Bildqualität',
    NL: 'Afbeeldingskwaliteit',
    IT: 'Qualità immagine',
  },
  'settings.cardFont': {
    EN: 'Card font',
    PT: 'Tipo de letra das cartas',
    FR: 'Police des cartes',
    ES: 'Fuente de las cartas',
    DE: 'Kartenschrift',
    NL: 'Kaartlettertype',
    IT: 'Carattere delle carte',
  },
  'settings.cardFontHint': {
    EN: 'Used for all card text, on screen and in the PDF. Demo fonts fall back to a readable font for numbers and accents.',
    PT: 'Usado em todo o texto das cartas, no ecrã e no PDF. Os tipos de demonstração usam uma letra legível para números e acentos.',
    FR: 'Utilisée pour tout le texte des cartes, à l’écran et dans le PDF. Les polices de démonstration utilisent une police lisible pour les chiffres et les accents.',
    ES: 'Se usa en todo el texto de las cartas, en pantalla y en el PDF. Las fuentes de demostración usan una fuente legible para números y acentos.',
    DE: 'Wird für den gesamten Kartentext verwendet, am Bildschirm und im PDF. Demo-Schriften nutzen für Zahlen und Akzente eine lesbare Schrift.',
    NL: 'Wordt gebruikt voor alle kaarttekst, op het scherm en in de pdf. Demoletters gebruiken een leesbaar lettertype voor cijfers en accenten.',
    IT: 'Usato per tutto il testo delle carte, a schermo e nel PDF. I font dimostrativi usano un carattere leggibile per numeri e accenti.',
  },
  'settings.cardFontBundled': {
    EN: 'Bundled fonts',
    PT: 'Tipos incluídos',
    FR: 'Polices intégrées',
    ES: 'Fuentes incluidas',
    DE: 'Mitgelieferte Schriften',
    NL: 'Ingebouwde lettertypen',
    IT: 'Font inclusi',
  },
  'settings.cardFontSystem': {
    EN: 'System fonts',
    PT: 'Tipos do sistema',
    FR: 'Polices du système',
    ES: 'Fuentes del sistema',
    DE: 'Systemschriften',
    NL: 'Systeemlettertypen',
    IT: 'Font di sistema',
  },
  'settings.cardFontSystemHint': {
    EN: 'Only system fonts for your device platform are listed. They render on screen when installed. PDF export embeds them only in Chromium-based browsers with font access; otherwise standard fonts are used.',
    PT: 'Só são listados os tipos do sistema da plataforma do teu dispositivo. Aparecem no ecrã quando estão instalados. O PDF só os incorpora em navegadores baseados em Chromium com acesso a tipos; caso contrário usa os tipos padrão.',
    FR: 'Seules les polices système de votre plateforme sont listées. Elles s’affichent à l’écran si elles sont installées. Le PDF ne les intègre que dans les navigateurs Chromium avec accès aux polices ; sinon, les polices standard sont utilisées.',
    ES: 'Solo se muestran las fuentes del sistema de tu plataforma. Se ven en pantalla cuando están instaladas. El PDF solo las incrusta en navegadores basados en Chromium con acceso a fuentes; de lo contrario se usan fuentes estándar.',
    DE: 'Es werden nur Systemschriften deiner Plattform aufgelistet. Sie werden am Bildschirm angezeigt, wenn sie installiert sind. Das PDF bettet sie nur in Chromium-basierten Browsern mit Schriftzugriff ein; andernfalls werden Standardschriften verwendet.',
    NL: 'Alleen systeemlettertypen van jouw platform worden vermeld. Ze worden op het scherm weergegeven als ze zijn geïnstalleerd. De pdf sluit ze alleen in bij op Chromium gebaseerde browsers met toegang tot lettertypen; anders worden standaardlettertypen gebruikt.',
    IT: 'Sono elencati solo i font di sistema della tua piattaforma. Vengono mostrati a schermo se installati. Il PDF li incorpora solo nei browser basati su Chromium con accesso ai font; altrimenti usa i font standard.',
  },
  'settings.pdfInfo': {
    EN: 'Every card is exported as one full PDF page at exactly {width} x {height} mm ({language}), with no page margins.',
    PT: 'Cada carta é exportada como uma página PDF completa com exatamente {width} x {height} mm ({language}), sem margens.',
    FR: 'Chaque carte est exportée sur une page PDF complète de exactement {width} x {height} mm ({language}), sans marges.',
    ES: 'Cada carta se exporta como una página PDF completa de exactamente {width} x {height} mm ({language}), sin márgenes.',
    DE: 'Jede Karte wird als vollständige PDF-Seite mit genau {width} x {height} mm ({language}) ohne Seitenränder exportiert.',
    NL: 'Elke kaart wordt geëxporteerd als één volledige PDF-pagina van precies {width} x {height} mm ({language}), zonder marges.',
    IT: 'Ogni carta viene esportata come una pagina PDF completa di esattamente {width} x {height} mm ({language}), senza margini.',
  },
  'settings.backupPanel': {
    EN: 'Backup & Restore',
    PT: 'Backup e restauro',
    FR: 'Sauvegarde et restauration',
    ES: 'Copia y restauración',
    DE: 'Backup & Wiederherstellung',
    NL: 'Back-up en herstel',
    IT: 'Backup e ripristino',
  },
  'settings.backupText': {
    EN: 'Everything is stored locally in your browser. Export a JSON backup to move your collection between browsers or devices.',
    PT: 'Tudo é guardado localmente no seu navegador. Exporte um backup JSON para mover a coleção entre navegadores ou dispositivos.',
    FR: 'Tout est stocké localement dans votre navigateur. Exportez une sauvegarde JSON pour déplacer votre collection entre navigateurs ou appareils.',
    ES: 'Todo se guarda localmente en tu navegador. Exporta una copia JSON para mover tu colección entre navegadores o dispositivos.',
    DE: 'Alles wird lokal im Browser gespeichert. Exportiere ein JSON-Backup, um deine Sammlung zwischen Browsern oder Geräten zu übertragen.',
    NL: 'Alles wordt lokaal in je browser opgeslagen. Exporteer een JSON-back-up om je verzameling tussen browsers of apparaten te verplaatsen.',
    IT: 'Tutto è salvato localmente nel browser. Esporta un backup JSON per spostare la collezione tra browser o dispositivi.',
  },
  'settings.exportBackup': {
    EN: 'Export JSON Backup',
    PT: 'Exportar backup JSON',
    FR: 'Exporter la sauvegarde JSON',
    ES: 'Exportar copia JSON',
    DE: 'JSON-Backup exportieren',
    NL: 'JSON-back-up exporteren',
    IT: 'Esporta backup JSON',
  },
  'settings.importBackup': {
    EN: 'Import JSON Backup',
    PT: 'Importar backup JSON',
    FR: 'Importer une sauvegarde JSON',
    ES: 'Importar copia JSON',
    DE: 'JSON-Backup importieren',
    NL: 'JSON-back-up importeren',
    IT: 'Importa backup JSON',
  },
  'settings.demoPanel': {
    EN: 'Demo Cards',
    PT: 'Cartas de demonstração',
    FR: 'Cartes de démonstration',
    ES: 'Cartas de demostración',
    DE: 'Demo-Karten',
    NL: 'Demokaarten',
    IT: 'Carte dimostrative',
  },
  'settings.restoreDemo': {
    EN: 'Restore Demo Cards',
    PT: 'Restaurar cartas de demonstração',
    FR: 'Restaurer les cartes de démonstration',
    ES: 'Restaurar cartas de demostración',
    DE: 'Demo-Karten wiederherstellen',
    NL: 'Demokaarten herstellen',
    IT: 'Ripristina carte dimostrative',
  },
  'settings.dangerPanel': {
    EN: 'Danger Zone',
    PT: 'Zona de risco',
    FR: 'Zone sensible',
    ES: 'Zona de peligro',
    DE: 'Gefahrenzone',
    NL: 'Gevarenzone',
    IT: 'Zona a rischio',
  },
  'settings.dangerText': {
    EN: 'Deleting local data cannot be undone. Export a backup first if you may need your cards later.',
    PT: 'A exclusão dos dados locais não pode ser desfeita. Exporte um backup primeiro se puder precisar das cartas mais tarde.',
    FR: 'La suppression des données locales est irréversible. Exportez d’abord une sauvegarde si vous pourriez avoir besoin de vos cartes.',
    ES: 'Eliminar los datos locales no se puede deshacer. Exporta antes una copia si puedes necesitar tus cartas más adelante.',
    DE: 'Das Löschen lokaler Daten kann nicht rückgängig gemacht werden. Exportiere zuerst ein Backup, falls du deine Karten später brauchst.',
    NL: 'Het verwijderen van lokale gegevens kan niet ongedaan worden gemaakt. Exporteer eerst een back-up als je je kaarten later nodig hebt.',
    IT: 'L’eliminazione dei dati locali non può essere annullata. Esporta prima un backup se potresti aver bisogno delle carte.',
  },
  'settings.statusReset': {
    EN: 'Settings were reset to their defaults.',
    PT: 'As configurações foram restauradas para os padrões.',
    FR: 'Les paramètres ont été réinitialisés.',
    ES: 'Se restablecieron los ajustes predeterminados.',
    DE: 'Die Einstellungen wurden zurückgesetzt.',
    NL: 'De instellingen zijn teruggezet naar de standaardwaarden.',
    IT: 'Le impostazioni sono state ripristinate.',
  },
  'settings.statusBackupExported': {
    EN: 'Backup with {count} cards was exported.',
    PT: 'Foi exportado um backup com {count} cartas.',
    FR: 'Sauvegarde de {count} cartes exportée.',
    ES: 'Se exportó una copia con {count} cartas.',
    DE: 'Backup mit {count} Karten wurde exportiert.',
    NL: 'Back-up met {count} kaarten is geëxporteerd.',
    IT: 'Esportato un backup con {count} carte.',
  },
  'settings.statusImported': {
    EN: 'Imported {count} cards.',
    PT: 'Foram importadas {count} cartas.',
    FR: '{count} cartes importées.',
    ES: 'Se importaron {count} cartas.',
    DE: '{count} Karten importiert.',
    NL: '{count} kaarten geïmporteerd.',
    IT: 'Importate {count} carte.',
  },
  'settings.statusRestored': {
    EN: 'Restored {count} demo cards.',
    PT: 'Foram restauradas {count} cartas de demonstração.',
    FR: '{count} cartes de démonstration restaurées.',
    ES: 'Se restauraron {count} cartas de demostración.',
    DE: '{count} Demo-Karten wiederhergestellt.',
    NL: '{count} demokaarten hersteld.',
    IT: 'Ripristinate {count} carte dimostrative.',
  },
  'settings.statusBackupFailed': {
    EN: 'The backup could not be exported. Please try again.',
    PT: 'Não foi possível exportar o backup. Tente novamente.',
    FR: 'La sauvegarde n’a pas pu être exportée. Veuillez réessayer.',
    ES: 'No se pudo exportar la copia. Inténtalo de nuevo.',
    DE: 'Das Backup konnte nicht exportiert werden. Bitte versuche es erneut.',
    NL: 'De back-up kon niet worden geëxporteerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile esportare il backup. Riprova.',
  },
  'settings.statusImportFailed': {
    EN: 'The backup could not be imported. Please try again.',
    PT: 'Não foi possível importar o backup. Tente novamente.',
    FR: 'La sauvegarde n’a pas pu être importée. Veuillez réessayer.',
    ES: 'No se pudo importar la copia. Inténtalo de nuevo.',
    DE: 'Das Backup konnte nicht importiert werden. Bitte versuche es erneut.',
    NL: 'De back-up kon niet worden geïmporteerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile importare il backup. Riprova.',
  },
  'settings.statusRestoreFailed': {
    EN: 'The demo cards could not be restored. Please try again.',
    PT: 'Não foi possível restaurar as cartas de demonstração. Tente novamente.',
    FR: 'Les cartes de démonstration n’ont pas pu être restaurées. Veuillez réessayer.',
    ES: 'No se pudieron restaurar las cartas de demostración. Inténtalo de nuevo.',
    DE: 'Die Demo-Karten konnten nicht wiederhergestellt werden. Bitte versuche es erneut.',
    NL: 'De demokaarten konden niet worden hersteld. Probeer het opnieuw.',
    IT: 'Non è stato possibile ripristinare le carte dimostrative. Riprova.',
  },

  'store.storageUnavailable': {
    EN: 'Local storage is not available in this browser, so cards cannot be saved.',
    PT: 'O armazenamento local não está disponível neste navegador, por isso as cartas não podem ser guardadas.',
    FR: 'Le stockage local n’est pas disponible dans ce navigateur ; les cartes ne peuvent pas être enregistrées.',
    ES: 'El almacenamiento local no está disponible en este navegador, por lo que no se pueden guardar cartas.',
    DE: 'Der lokale Speicher ist in diesem Browser nicht verfügbar, daher können Karten nicht gespeichert werden.',
    NL: 'Lokale opslag is niet beschikbaar in deze browser, dus kaarten kunnen niet worden opgeslagen.',
    IT: 'L’archiviazione locale non è disponibile in questo browser, quindi le carte non possono essere salvate.',
  },
  'store.cardsLoadFailed': {
    EN: 'Cards could not be loaded from local storage.',
    PT: 'Não foi possível carregar as cartas do armazenamento local.',
    FR: 'Les cartes n’ont pas pu être chargées depuis le stockage local.',
    ES: 'No se pudieron cargar las cartas del almacenamiento local.',
    DE: 'Karten konnten nicht aus dem lokalen Speicher geladen werden.',
    NL: 'Kaarten konden niet uit de lokale opslag worden geladen.',
    IT: 'Non è stato possibile caricare le carte dall’archiviazione locale.',
  },
  'store.cardSaveFailed': {
    EN: 'The card could not be saved. Please try again.',
    PT: 'Não foi possível guardar a carta. Tente novamente.',
    FR: 'La carte n’a pas pu être enregistrée. Veuillez réessayer.',
    ES: 'No se pudo guardar la carta. Inténtalo de nuevo.',
    DE: 'Die Karte konnte nicht gespeichert werden. Bitte versuche es erneut.',
    NL: 'De kaart kon niet worden opgeslagen. Probeer het opnieuw.',
    IT: 'Non è stato possibile salvare la carta. Riprova.',
  },
  'store.cardDeleteFailed': {
    EN: 'The card could not be deleted. Please try again.',
    PT: 'Não foi possível excluir a carta. Tente novamente.',
    FR: 'La carte n’a pas pu être supprimée. Veuillez réessayer.',
    ES: 'No se pudo eliminar la carta. Inténtalo de nuevo.',
    DE: 'Die Karte konnte nicht gelöscht werden. Bitte versuche es erneut.',
    NL: 'De kaart kon niet worden verwijderd. Probeer het opnieuw.',
    IT: 'Non è stato possibile eliminare la carta. Riprova.',
  },
  'store.cardsDeleteFailed': {
    EN: 'The cards could not be deleted. Please try again.',
    PT: 'Não foi possível excluir as cartas. Tente novamente.',
    FR: 'Les cartes n’ont pas pu être supprimées. Veuillez réessayer.',
    ES: 'No se pudieron eliminar las cartas. Inténtalo de nuevo.',
    DE: 'Die Karten konnten nicht gelöscht werden. Bitte versuche es erneut.',
    NL: 'De kaarten konden niet worden verwijderd. Probeer het opnieuw.',
    IT: 'Non è stato possibile eliminare le carte. Riprova.',
  },
  'store.demoRestoreFailed': {
    EN: 'The demo cards could not be restored. Please try again.',
    PT: 'Não foi possível restaurar as cartas de demonstração. Tente novamente.',
    FR: 'Les cartes de démonstration n’ont pas pu être restaurées. Veuillez réessayer.',
    ES: 'No se pudieron restaurar las cartas de demostración. Inténtalo de nuevo.',
    DE: 'Die Demo-Karten konnten nicht wiederhergestellt werden. Bitte versuche es erneut.',
    NL: 'De demokaarten konden niet worden hersteld. Probeer het opnieuw.',
    IT: 'Non è stato possibile ripristinare le carte dimostrative. Riprova.',
  },
  'store.cardsImportFailed': {
    EN: 'The cards could not be imported. Please try again.',
    PT: 'Não foi possível importar as cartas. Tente novamente.',
    FR: 'Les cartes n’ont pas pu être importées. Veuillez réessayer.',
    ES: 'No se pudieron importar las cartas. Inténtalo de nuevo.',
    DE: 'Die Karten konnten nicht importiert werden. Bitte versuche es erneut.',
    NL: 'De kaarten konden niet worden geïmporteerd. Probeer het opnieuw.',
    IT: 'Non è stato possibile importare le carte. Riprova.',
  },
  'store.imageLoadFailed': {
    EN: 'Images could not be loaded from local storage.',
    PT: 'Não foi possível carregar as imagens do armazenamento local.',
    FR: 'Les images n’ont pas pu être chargées depuis le stockage local.',
    ES: 'No se pudieron cargar las imágenes del almacenamiento local.',
    DE: 'Bilder konnten nicht aus dem lokalen Speicher geladen werden.',
    NL: 'Afbeeldingen konden niet uit de lokale opslag worden geladen.',
    IT: 'Non è stato possibile caricare le immagini dall’archiviazione locale.',
  },
  'store.imageSaveFailed': {
    EN: 'The image could not be saved. Please try again.',
    PT: 'Não foi possível guardar a imagem. Tente novamente.',
    FR: 'L’image n’a pas pu être enregistrée. Veuillez réessayer.',
    ES: 'No se pudo guardar la imagen. Inténtalo de nuevo.',
    DE: 'Das Bild konnte nicht gespeichert werden. Bitte versuche es erneut.',
    NL: 'De afbeelding kon niet worden opgeslagen. Probeer het opnieuw.',
    IT: 'Non è stato possibile salvare l’immagine. Riprova.',
  },
  'store.imageDeleteFailed': {
    EN: 'The image could not be deleted. Please try again.',
    PT: 'Não foi possível excluir a imagem. Tente novamente.',
    FR: 'L’image n’a pas pu être supprimée. Veuillez réessayer.',
    ES: 'No se pudo eliminar la imagen. Inténtalo de nuevo.',
    DE: 'Das Bild konnte nicht gelöscht werden. Bitte versuche es erneut.',
    NL: 'De afbeelding kon niet worden verwijderd. Probeer het opnieuw.',
    IT: 'Non è stato possibile eliminare l’immagine. Riprova.',
  },
  'store.fixFields': {
    EN: 'Please fix the highlighted fields and try again.',
    PT: 'Corrija os campos destacados e tente novamente.',
    FR: 'Veuillez corriger les champs en surbrillance et réessayer.',
    ES: 'Corrige los campos resaltados e inténtalo de nuevo.',
    DE: 'Bitte korrigiere die markierten Felder und versuche es erneut.',
    NL: 'Corrigeer de gemarkeerde velden en probeer het opnieuw.',
    IT: 'Correggi i campi evidenziati e riprova.',
  },

  'error.titleRequired': {
    EN: 'Title is required.',
    PT: 'O título é obrigatório.',
    FR: 'Le titre est obligatoire.',
    ES: 'El título es obligatorio.',
    DE: 'Der Titel ist erforderlich.',
    NL: 'Titel is verplicht.',
    IT: 'Il titolo è obbligatorio.',
  },
  'error.titleTooLong': {
    EN: 'Title must be {max} characters or fewer.',
    PT: 'O título deve ter {max} caracteres ou menos.',
    FR: 'Le titre doit comporter au maximum {max} caractères.',
    ES: 'El título debe tener {max} caracteres o menos.',
    DE: 'Der Titel darf höchstens {max} Zeichen lang sein.',
    NL: 'De titel mag maximaal {max} tekens bevatten.',
    IT: 'Il titolo può contenere al massimo {max} caratteri.',
  },
  'error.actionRequired': {
    EN: 'Action is required.',
    PT: 'A ação é obrigatória.',
    FR: 'L’action est obligatoire.',
    ES: 'La acción es obligatoria.',
    DE: 'Die Aktion ist erforderlich.',
    NL: 'Actie is verplicht.',
    IT: 'L’azione è obbligatoria.',
  },
  'error.actionTooLong': {
    EN: 'Action must be {max} characters or fewer.',
    PT: 'A ação deve ter {max} caracteres ou menos.',
    FR: 'L’action doit comporter au maximum {max} caractères.',
    ES: 'La acción debe tener {max} caracteres o menos.',
    DE: 'Die Aktion darf höchstens {max} Zeichen lang sein.',
    NL: 'De actie mag maximaal {max} tekens bevatten.',
    IT: 'L’azione può contenere al massimo {max} caratteri.',
  },
  'error.subtitleTooLong': {
    EN: 'Subtitle must be {max} characters or fewer.',
    PT: 'O subtítulo deve ter {max} caracteres ou menos.',
    FR: 'Le sous-titre doit comporter au maximum {max} caractères.',
    ES: 'El subtítulo debe tener {max} caracteres o menos.',
    DE: 'Der Untertitel darf höchstens {max} Zeichen lang sein.',
    NL: 'De ondertitel mag maximaal {max} tekens bevatten.',
    IT: 'Il sottotitolo può contenere al massimo {max} caratteri.',
  },
  'error.attackRange': {
    EN: 'Attack must be a number between {min} and {max}.',
    PT: 'O ataque deve ser um número entre {min} e {max}.',
    FR: 'L’attaque doit être un nombre entre {min} et {max}.',
    ES: 'El ataque debe ser un número entre {min} y {max}.',
    DE: 'Der Angriff muss eine Zahl zwischen {min} und {max} sein.',
    NL: 'Aanval moet een getal tussen {min} en {max} zijn.',
    IT: 'L’attacco deve essere un numero tra {min} e {max}.',
  },
  'error.defenseRange': {
    EN: 'Defense must be a number between {min} and {max}.',
    PT: 'A defesa deve ser um número entre {min} e {max}.',
    FR: 'La défense doit être un nombre entre {min} et {max}.',
    ES: 'La defensa debe ser un número entre {min} y {max}.',
    DE: 'Die Verteidigung muss eine Zahl zwischen {min} und {max} sein.',
    NL: 'Verdediging moet een getal tussen {min} en {max} zijn.',
    IT: 'La difesa deve essere un numero tra {min} e {max}.',
  },
  'error.zoneInvalid': {
    EN: 'Select a valid zone.',
    PT: 'Selecione uma zona válida.',
    FR: 'Sélectionnez une zone valide.',
    ES: 'Selecciona una zona válida.',
    DE: 'Wähle eine gültige Zone.',
    NL: 'Selecteer een geldige zone.',
    IT: 'Seleziona una zona valida.',
  },
  'error.imageFormat': {
    EN: 'The image format is not supported.',
    PT: 'O formato da imagem não é suportado.',
    FR: 'Le format de l’image n’est pas pris en charge.',
    ES: 'El formato de imagen no es compatible.',
    DE: 'Das Bildformat wird nicht unterstützt.',
    NL: 'Het afbeeldingsformaat wordt niet ondersteund.',
    IT: 'Il formato dell’immagine non è supportato.',
  },
  'error.starsRange': {
    EN: 'Stars must be a whole number between {min} and {max}.',
    PT: 'As estrelas devem ser um número inteiro entre {min} e {max}.',
    FR: 'Les étoiles doivent être un nombre entier entre {min} et {max}.',
    ES: 'Las estrellas deben ser un número entero entre {min} y {max}.',
    DE: 'Sterne müssen eine ganze Zahl zwischen {min} und {max} sein.',
    NL: 'Sterren moeten een heel getal tussen {min} en {max} zijn.',
    IT: 'Le stelle devono essere un numero intero tra {min} e {max}.',
  },
  'error.translationTooLong': {
    EN: 'A translation exceeds the allowed length (title up to {title}, action up to {action}).',
    PT: 'Uma tradução excede o comprimento permitido (título até {title}, ação até {action}).',
    FR: 'Une traduction dépasse la longueur autorisée (titre : {title}, action : {action}).',
    ES: 'Una traducción supera la longitud permitida (título: {title}, acción: {action}).',
    DE: 'Eine Übersetzung überschreitet die zulässige Länge (Titel {title}, Aktion {action}).',
    NL: 'Een vertaling overschrijdt de toegestane lengte (titel {title}, actie {action}).',
    IT: 'Una traduzione supera la lunghezza consentita (titolo {title}, azione {action}).',
  },

  'error.imageType': {
    EN: 'The file is not a valid PNG, JPEG or WebP image.',
    PT: 'O ficheiro não é uma imagem PNG, JPEG ou WebP válida.',
    FR: 'Le fichier n’est pas une image PNG, JPEG ou WebP valide.',
    ES: 'El archivo no es una imagen PNG, JPEG o WebP válida.',
    DE: 'Die Datei ist kein gültiges PNG-, JPEG- oder WebP-Bild.',
    NL: 'Het bestand is geen geldige PNG-, JPEG- of WebP-afbeelding.',
    IT: 'Il file non è un’immagine PNG, JPEG o WebP valida.',
  },
  'error.imageSize': {
    EN: 'Image must be 5 MB or smaller.',
    PT: 'A imagem deve ter 5 MB ou menos.',
    FR: 'L’image doit faire 5 Mo ou moins.',
    ES: 'La imagen debe ser de 5 MB o menos.',
    DE: 'Das Bild darf höchstens 5 MB groß sein.',
    NL: 'De afbeelding mag maximaal 5 MB zijn.',
    IT: 'L’immagine deve essere di 5 MB o meno.',
  },
  'error.imageRead': {
    EN: 'The selected file could not be read as an image.',
    PT: 'Não foi possível ler o ficheiro selecionado como imagem.',
    FR: 'Le fichier sélectionné n’a pas pu être lu comme image.',
    ES: 'No se pudo leer el archivo seleccionado como imagen.',
    DE: 'Die ausgewählte Datei konnte nicht als Bild gelesen werden.',
    NL: 'Het geselecteerde bestand kon niet als afbeelding worden gelezen.',
    IT: 'Non è stato possibile leggere il file selezionato come immagine.',
  },
  'error.imageProcess': {
    EN: 'The selected file could not be processed.',
    PT: 'Não foi possível processar o ficheiro selecionado.',
    FR: 'Le fichier sélectionné n’a pas pu être traité.',
    ES: 'No se pudo procesar el archivo seleccionado.',
    DE: 'Die ausgewählte Datei konnte nicht verarbeitet werden.',
    NL: 'Het geselecteerde bestand kon niet worden verwerkt.',
    IT: 'Non è stato possibile elaborare il file selezionato.',
  },
  'error.imageInvalidData': {
    EN: 'Invalid image data.',
    PT: 'Dados de imagem inválidos.',
    FR: 'Données d’image non valides.',
    ES: 'Datos de imagen no válidos.',
    DE: 'Ungültige Bilddaten.',
    NL: 'Ongeldige afbeeldingsgegevens.',
    IT: 'Dati immagine non validi.',
  },
  'error.imageReadBytes': {
    EN: 'The selected file could not be read.',
    PT: 'Não foi possível ler o ficheiro selecionado.',
    FR: 'Le fichier sélectionné n’a pas pu être lu.',
    ES: 'No se pudo leer el archivo seleccionado.',
    DE: 'Die ausgewählte Datei konnte nicht gelesen werden.',
    NL: 'Het geselecteerde bestand kon niet worden gelezen.',
    IT: 'Non è stato possibile leggere il file selezionato.',
  },

  'error.backupInvalid': {
    EN: 'This file is not a valid Card Generator backup.',
    PT: 'Este ficheiro não é um backup válido do Card Generator.',
    FR: 'Ce fichier n’est pas une sauvegarde Card Generator valide.',
    ES: 'Este archivo no es una copia de seguridad válida de Card Generator.',
    DE: 'Diese Datei ist kein gültiges Card-Generator-Backup.',
    NL: 'Dit bestand is geen geldige Card Generator-back-up.',
    IT: 'Questo file non è un backup valido di Card Generator.',
  },
  'error.backupCardInvalid': {
    EN: 'The backup file contains an invalid card.',
    PT: 'O ficheiro de backup contém uma carta inválida.',
    FR: 'Le fichier de sauvegarde contient une carte non valide.',
    ES: 'El archivo de copia contiene una carta no válida.',
    DE: 'Die Backup-Datei enthält eine ungültige Karte.',
    NL: 'Het back-upbestand bevat een ongeldige kaart.',
    IT: 'Il file di backup contiene una carta non valida.',
  },
  'error.backupVersion': {
    EN: 'This backup file version is not supported.',
    PT: 'A versão deste ficheiro de backup não é suportada.',
    FR: 'Cette version de fichier de sauvegarde n’est pas prise en charge.',
    ES: 'Esta versión de archivo de copia no es compatible.',
    DE: 'Diese Backup-Dateiversion wird nicht unterstützt.',
    NL: 'Deze versie van het back-upbestand wordt niet ondersteund.',
    IT: 'Questa versione del file di backup non è supportata.',
  },
  'error.backupRead': {
    EN: 'The selected file could not be read.',
    PT: 'Não foi possível ler o ficheiro selecionado.',
    FR: 'Le fichier sélectionné n’a pas pu être lu.',
    ES: 'No se pudo leer el archivo seleccionado.',
    DE: 'Die ausgewählte Datei konnte nicht gelesen werden.',
    NL: 'Het geselecteerde bestand kon niet worden gelezen.',
    IT: 'Non è stato possibile leggere il file selezionato.',
  },

  'error.csvRead': {
    EN: 'The selected CSV file could not be read.',
    PT: 'Não foi possível ler o ficheiro CSV selecionado.',
    FR: 'Le fichier CSV sélectionné n’a pas pu être lu.',
    ES: 'No se pudo leer el archivo CSV seleccionado.',
    DE: 'Die ausgewählte CSV-Datei konnte nicht gelesen werden.',
    NL: 'Het geselecteerde CSV-bestand kon niet worden gelezen.',
    IT: 'Non è stato possibile leggere il file CSV selezionato.',
  },
  'error.csvEmpty': {
    EN: 'The CSV does not contain any card rows.',
    PT: 'O CSV não contém linhas de cartas.',
    FR: 'Le CSV ne contient aucune ligne de carte.',
    ES: 'El CSV no contiene filas de cartas.',
    DE: 'Die CSV enthält keine Kartenzeilen.',
    NL: 'De CSV bevat geen kaartrijen.',
    IT: 'Il CSV non contiene righe di carte.',
  },
  'error.csvMissingColumns': {
    EN: 'The CSV is missing required column(s): {columns}.',
    PT: 'Faltam colunas obrigatórias no CSV: {columns}.',
    FR: 'Colonnes obligatoires manquantes dans le CSV : {columns}.',
    ES: 'Faltan columnas obligatorias en el CSV: {columns}.',
    DE: 'In der CSV fehlen erforderliche Spalten: {columns}.',
    NL: 'In de CSV ontbreken verplichte kolommen: {columns}.',
    IT: 'Nel CSV mancano colonne obbligatorie: {columns}.',
  },
  'error.csvTooManyRows': {
    EN: 'The CSV contains more than {max} rows.',
    PT: 'O CSV contém mais de {max} linhas.',
    FR: 'Le CSV contient plus de {max} lignes.',
    ES: 'El CSV contiene más de {max} filas.',
    DE: 'Die CSV enthält mehr als {max} Zeilen.',
    NL: 'De CSV bevat meer dan {max} rijen.',
    IT: 'Il CSV contiene più di {max} righe.',
  },
  'error.csvInvalidRows': {
    EN: 'The CSV contains {count} invalid row(s).',
    PT: 'O CSV contém {count} linha(s) inválida(s).',
    FR: 'Le CSV contient {count} ligne(s) non valide(s).',
    ES: 'El CSV contiene {count} fila(s) no válida(s).',
    DE: 'Die CSV enthält {count} ungültige Zeile(n).',
    NL: 'De CSV bevat {count} ongeldige rij(en).',
    IT: 'Il CSV contiene {count} riga/righe non valide.',
  },
  'error.csvRow': {
    EN: 'Row {row}: {message}',
    PT: 'Linha {row}: {message}',
    FR: 'Ligne {row} : {message}',
    ES: 'Fila {row}: {message}',
    DE: 'Zeile {row}: {message}',
    NL: 'Rij {row}: {message}',
    IT: 'Riga {row}: {message}',
  },
  'error.pdfEmpty': {
    EN: 'Select at least one card to export.',
    PT: 'Selecione pelo menos uma carta para exportar.',
    FR: 'Sélectionnez au moins une carte à exporter.',
    ES: 'Selecciona al menos una carta para exportar.',
    DE: 'Wähle mindestens eine Karte zum Exportieren.',
    NL: 'Selecteer minstens één kaart om te exporteren.',
    IT: 'Seleziona almeno una carta da esportare.',
  },
} as const satisfies Record<string, Messages>

export type MessageKey = keyof typeof MESSAGES

/** Replaces `{name}` placeholders in a translated message. */
export function translate(
  key: MessageKey,
  language: Language,
  params?: Record<string, string | number>,
): string {
  const entry = MESSAGES[key]
  const template: string = entry?.[language] ?? entry?.EN ?? key

  if (!params) return template

  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in params ? String(params[name]) : match,
  )
}
